"""initial_schema

Revision ID: d5d0d99d2cf0
Revises: 
Create Date: 2026-01-19 16:18:13.318071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5d0d99d2cf0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('size', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_table('role_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('title_patterns', sa.JSON(), nullable=False),
    sa.Column('positive_keywords', sa.JSON(), nullable=False),
    sa.Column('negative_keywords', sa.JSON(), nullable=False),
    sa.Column('seniority_config', sa.JSON(), nullable=True),
    sa.Column('relevance_threshold', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_profiles_id'), 'role_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_role_profiles_slug'), 'role_profiles', ['slug'], unique=True)
    op.create_table('scraper_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_slug', sa.String(length=100), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('config_overrides', sa.JSON(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=True),
    sa.Column('total_runs', sa.Integer(), nullable=True),
    sa.Column('total_jobs_found', sa.Integer(), nullable=True),
    sa.Column('schedule_cron', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraper_configs_company_slug'), 'scraper_configs', ['company_slug'], unique=True)
    op.create_index(op.f('ix_scraper_configs_id'), 'scraper_configs', ['id'], unique=False)
    op.create_index(op.f('ix_scraper_configs_is_enabled'), 'scraper_configs', ['is_enabled'], unique=False)
    op.create_table('scraper_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_slug', sa.String(length=100), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('jobs_found', sa.Integer(), nullable=True),
    sa.Column('jobs_new', sa.Integer(), nullable=True),
    sa.Column('jobs_updated', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('pages_scraped', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_type', sa.String(length=50), nullable=True),
    sa.Column('run_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('celery_task_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraper_runs_company_slug'), 'scraper_runs', ['company_slug'], unique=False)
    op.create_index(op.f('ix_scraper_runs_id'), 'scraper_runs', ['id'], unique=False)
    op.create_index(op.f('ix_scraper_runs_run_at'), 'scraper_runs', ['run_at'], unique=False)
    op.create_index(op.f('ix_scraper_runs_success'), 'scraper_runs', ['success'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('relationship_type', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_id'), 'contacts', ['id'], unique=False)
    op.create_table('ingestion_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('ats_type', sa.String(length=50), nullable=False),
    sa.Column('ats_company_slug', sa.String(length=255), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('career_page_url', sa.String(length=500), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('last_successful_at', sa.DateTime(), nullable=True),
    sa.Column('job_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_sources_id'), 'ingestion_sources', ['id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('job_url', sa.String(length=500), nullable=True),
    sa.Column('job_description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('date_found', sa.Date(), nullable=True),
    sa.Column('date_applied', sa.Date(), nullable=True),
    sa.Column('excitement_level', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('external_job_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('posted_date', sa.DateTime(), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role_profile_id', sa.Integer(), nullable=True),
    sa.Column('custom_preferences', sa.JSON(), nullable=True),
    sa.Column('preferred_locations', sa.JSON(), nullable=True),
    sa.Column('target_seniority', sa.String(length=50), nullable=True),
    sa.Column('min_salary', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['role_profile_id'], ['role_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('interviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('interview_date', sa.DateTime(), nullable=False),
    sa.Column('interview_type', sa.String(length=50), nullable=True),
    sa.Column('interviewer_names', sa.String(length=500), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('outcome', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interviews_id'), 'interviews', ['id'], unique=False)
    op.create_table('job_relevance_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('is_relevant', sa.Boolean(), nullable=False),
    sa.Column('score_breakdown', sa.JSON(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('role_profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_relevance_scores_id'), 'job_relevance_scores', ['id'], unique=False)
    op.create_index(op.f('ix_job_relevance_scores_is_relevant'), 'job_relevance_scores', ['is_relevant'], unique=False)
    op.create_index(op.f('ix_job_relevance_scores_job_id'), 'job_relevance_scores', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_relevance_scores_relevance_score'), 'job_relevance_scores', ['relevance_score'], unique=False)
    op.create_index(op.f('ix_job_relevance_scores_user_id'), 'job_relevance_scores', ['user_id'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('note_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_id'), 'notes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notes_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_job_relevance_scores_user_id'), table_name='job_relevance_scores')
    op.drop_index(op.f('ix_job_relevance_scores_relevance_score'), table_name='job_relevance_scores')
    op.drop_index(op.f('ix_job_relevance_scores_job_id'), table_name='job_relevance_scores')
    op.drop_index(op.f('ix_job_relevance_scores_is_relevant'), table_name='job_relevance_scores')
    op.drop_index(op.f('ix_job_relevance_scores_id'), table_name='job_relevance_scores')
    op.drop_table('job_relevance_scores')
    op.drop_index(op.f('ix_interviews_id'), table_name='interviews')
    op.drop_table('interviews')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_ingestion_sources_id'), table_name='ingestion_sources')
    op.drop_table('ingestion_sources')
    op.drop_index(op.f('ix_contacts_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_scraper_runs_success'), table_name='scraper_runs')
    op.drop_index(op.f('ix_scraper_runs_run_at'), table_name='scraper_runs')
    op.drop_index(op.f('ix_scraper_runs_id'), table_name='scraper_runs')
    op.drop_index(op.f('ix_scraper_runs_company_slug'), table_name='scraper_runs')
    op.drop_table('scraper_runs')
    op.drop_index(op.f('ix_scraper_configs_is_enabled'), table_name='scraper_configs')
    op.drop_index(op.f('ix_scraper_configs_id'), table_name='scraper_configs')
    op.drop_index(op.f('ix_scraper_configs_company_slug'), table_name='scraper_configs')
    op.drop_table('scraper_configs')
    op.drop_index(op.f('ix_role_profiles_slug'), table_name='role_profiles')
    op.drop_index(op.f('ix_role_profiles_id'), table_name='role_profiles')
    op.drop_table('role_profiles')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
